// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

// Same order as Next.js: .env first, then .env.local (which overrides) - otherwise
// DATABASE_URL tends to be missing for `prisma migrate` only.
loadEnv({ path: resolve(process.cwd(), ".env") });
loadEnv({ path: resolve(process.cwd(), ".env.local"), override: true });

// `prisma generate` - called from postinstall, among others - needs no running DB, only
// a syntactically valid URL. GitHub Actions often has no .env, but sets CI.
const placeholderForGenerateOnly =
  "postgresql://placeholder:placeholder@127.0.0.1:5432/placeholder";

const databaseUrl =
  process.env["DATABASE_URL"]?.trim() ||
  (process.env["CI"] === "true" ? placeholderForGenerateOnly : undefined);

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL ist nicht gesetzt. Lege .env oder .env.local an (siehe .env.example) und starte z. B. Docker-Postgres."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
